#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "Ejecutando hooks pre-commit..."

# Comprueba si hay archivos para 'lint-staged'
# Esto evita errores si no hay archivos 'staged' que coincidan con los patrones de lint-staged
output=$(npx lint-staged --allow-empty 2>&1)
result=$?

echo "$output"

if [ $result -ne 0 ]; then
  echo "------------------------------------------------------------------"
  echo "¡Error en los hooks pre-commit! Revisa los mensajes anteriores."
  echo "Algunos problemas pueden ser arreglados automáticamente por los linters/formateadores."
  echo "Asegúrate de añadir los cambios hechos por ellos al staging (git add .)."
  echo "------------------------------------------------------------------"
  exit 1
fi

echo "Hooks pre-commit finalizados con éxito."
exit 0